### PR TITLE
Update unicode character lists and add support for diacritics, Hangul characters, and Japanese wide-width punctuation

### PR DESCRIPTION
**Pull request by tobobo**
We made some modifications to this library in order to support a few more scripts we found didn't quite work before—thought you might want to take a look.

### CODE REVIEW

**Comment by jeremys** [comment]
Hey, I'm sorry I missed your mail. Did you closed because it's not needed anymore?

**Comment by tobobo** [comment]
Ah, no @jeremys I just closed it as it had been open for a while and was cleaning up my PRs. If you think it would be a good addition I'd be happy to reopen it.

**Comment by jeremys** [comment]
Your changes look great so I think it would be nice to merge those changes!

**Comment by tobobo** [comment]
cool! :) I've reopened the PR if you want to merge it.

**Comment by jeremys** [comment]
Thanks a lot! I'll update the npm package soon.

**Pull request merged**
